[project]
name = "telegram-bot"
version = "2.0.0"
description = "Telegram Bot Service"
requires-python = ">=3.10"

##########################################################
# BLACK
##########################################################

[tool.black]
line-length = 100
target-version = ["py310"]

##########################################################
# RUFF
##########################################################

[tool.ruff]

line-length = 100
target-version = "py310"

exclude = [
    ".venv",
    ".git",
    "__pycache__",
    "downloads",
    "logs",
    "sessions",
    "backups"
]

[tool.ruff.lint]

select = [
    "E",
    "F",
    "I",
    "UP",
    "B"
]

ignore = [
    "E501"
]

##########################################################
# ISORT
##########################################################

[tool.isort]

profile = "black"

line_length = 100

known_first_party = [
    "bots",
    "common",
    "configs",
    "cron",
    "db"
]

##########################################################
# PYTEST
##########################################################

[tool.pytest.ini_options]

pythonpath = [
    "."
]

testpaths = [
    "tests"
]

##########################################################
# MYPY
##########################################################

[tool.mypy]

python_version = "3.10"

ignore_missing_imports = true

warn_unused_configs = true

warn_return_any = false

check_untyped_defs = false

exclude = [
    ".venv",
    "downloads",
    "logs",
    "sessions",
    "backups"
]

##########################################################
# pyright
##########################################################

[tool.pyright]
typeCheckingMode = "basic"

reportPrivateImportUsage = false

reportUnknownMemberType = false

reportUnknownVariableType = false

reportUnknownArgumentType = false

reportUnknownParameterType = false

reportUnknownLambdaType = false

reportUnknownVariableType = false